---
- name: MariaDB | root password | set
  shell: mysql -e "UPDATE mysql.user SET Password=PASSWORD('{{ mariadb_root_password }}') WHERE User='root';"

- name: MariaDB | anonymous users | remove
  shell: mysql -e "DELETE FROM mysql.user WHERE User='';"
  ignore_errors: yes

- name: MariaDB | non-local root users | remove
  shell: mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
  when: not mariadb_remote_root_access
  ignore_errors: yes

- name: MariaDB | test database | remove
  shell: mysql -e "DROP DATABASE test;"
  ignore_errors: yes

- name: MariaDB | privileges | test database | remove
  shell: mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
  ignore_errors: yes

- name: MariaDB | privileges | flush
  shell: mysql -e "FLUSH PRIVILEGES;"

- name: MariaDB | root profile | Configure
  template: src=my.cnf.j2 dest={{ mariadb_client_config }} owner=root group=root mode=0600
            backup=yes
